ssh_key: ENC[AES256_GCM,data:d1muIQphr+t8XUKK1VZr/Hnu8LRC4/ALZBx9iPDznXw/jNc98X/fqxveYs24DmqXRkyjTO2R71cCX1+ygse3S2PyqIdL85IqaCf82HFIkEfd+PFClEBrXqO+C19CmT4x8Gr8IwtbF+wDw/GVx7bbdtJEV/1QTrV5ObEFWhvlFqQdeyL4YPb6jmCgXpCJo5fpe9G+VLdqIMg6jHtcjcAXhMK61yj3XQcHg2dK2FhHjUevDXlLewJU9ad94oS8irO38NLxvw/3/qlMMo4rgBRBDdoa89hLW0Xrk/LraTA36JUknxGF3xvjZRj1PckCXGNokPiPLUHvXGRBKnEDlLBJmrgpRO3N1S2Wy+HiQMdsW6YzPVMaWA8BY46CtCcpEZG+44OZHXMcgOvHnhiar6JrCi8o/E2SEybN3Q3u3orfgKtbThYEgsfWGkmoegJEo1tR0jLc7ln57eHQKPbdUbnY/0rDv6iBJ4D0vs4EMcuGpoyYJCMEkmyqSVvdvjjTYqO0hhJJar7YlBvdTafzF2Z2FKs3jMk+ud9JJRfw,iv:mYZEIamfmdscA/SpG2BkblnyALM77U4+0Rc/+180wrg=,tag:JnwvYPJFIbvpPusUuvegyg==,type:str]
ssh_key.pub: ENC[AES256_GCM,data:wSWWoc6jtreFJFiAVShXdzLaPNPaFv6NvN5VHvYk9u7GTgasZu3+Ya4N9L2VDClQMa7X2M6RxhKBBDJN0jW+bhMBktAIyhDaUDAyyJmyx6wBpri/7RxtGUFMQYdyXL8=,iv:F0R7vgppcUcIlLSVQ0xfTyHtsf2FqZ8qvktNdez0P/o=,tag:pVRcUgI/mJRWFt9PUYL2+Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArMTBHUWV4dmpJVk1Xcmlx
            Sm95c0NNQno3RDVPSWRNMTNXaWVtYk9RUHlFCldWclh0clFNMUl0aWRjcURZeXlR
            OG11TnB5bFZsY0tBOSs4OGtIa0dCUFkKLS0tIEFjZVc5KzJkM1c2UFBqWW1rRlcz
            VnVsTkdsQUxYbE4zRVRkclQ4QjJ3K3cK2hcipH2hjDCaHmdXNea2B1TalnK8Vi6i
            2C1aUSxQN05FaOWNrVpSCmxwzRbU0Alh70LjPxLaLBZpTylDwl4l5A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x3h3ukfqnmkm0rjet6pm57e5qaxhr57z0tsrwgmv49mh5k6gw50qtfe4xd
    lastmodified: "2026-05-14T22:35:54Z"
    mac: ENC[AES256_GCM,data:SZDSaLlNR9gTrRZ2IzCRCFdyHqyjF+k4Kfl+/z55CPknhDT5c3nsYho8z8+j8itpmI4xrA5VPgdqAT/i8d0FU50XhMLumXU2zAA3wwGGcaqYiQJmcaFwltSrG1u2rmu16psjJsCaKqf6vTXuyfionaO49sGY4HhYIIedx0YxQH4=,iv:LO8C5ytvaqrxr2/bVzSAszOKOR50lIMTW6z+Fuzk9tI=,tag:ZwCfKroP4Bsl+gK45LBlWA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
